### ISSUE TITLE
Movie support ?

### ISSUE THREAD

**Issue by JamesDAdams** [Zggis/plex-tvtime#11]
Hi,

That would be nice tha have movie support :)

Thanks for your soft !

**Comment by JamesDAdams** [comment]
i read the read me...

**Comment by Zggis** [comment]
Yes the original TVTime website apparently did not support this, but they recently updated their website completely https://github.com/Zggis/plex-tvtime/issues/8, the new website may allow movie support per what you noted in https://github.com/Zggis/plex-tvtime/issues/13
