### ISSUE TITLE
Movie posibility ?

### ISSUE THREAD

**Issue by JamesDAdams** [Zggis/plex-tvtime#13]
Hi,

For the movie is not possible to do this : 

1. Get the movie id from plex hook
2. Call the Tvtime uri with the movid id : https://app.tvtime.com/sidecar?o=https%3A%2F%2Fsearch.tvtime.com%2Fv1%2Fsearch%2Fseries%2Cmovie&q=MOVIE-ID&offset=0&limit=1
3. Select the first result in the table and get UUID
4. Call this uri with the UUID : https://app.tvtime.com/sidecar?o=https%3A%2F%2Fmsapi.tvtime.com%2Fprod%2Fv1%2Ftracking%2UUID%2Ffollow

**Comment by Zggis** [comment]
I will look into this

**Comment by Zggis** [comment]
Movie support has been added as of v2.1.0. Please pull the latest tag and add an environment variable for TRACK_MOVIES=true
