### ISSUE TITLE
Can't change port

### ISSUE THREAD

**Issue by ChoyDarren** [Zggis/plex-tvtime#15]
I'm running this through Docker on my Synology NAS, created by running this script:

```
docker run -d \
--name=PlexTVTime \
-e SPRING_CONFIG_LOCATION=/config/application.yaml \
-v /volume1/docker/plextvtime:/config \
--net=host \
-p 8081:8081 \
zggis/plex-tvtime:latest
```

However, the port doesn't change and keeps starting on port 8080, which is already being used. Can I change the port or am I doing it incorrectly?

Logs:

```
Starting ProtocolHandler ["http-nio-8080"]
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'
Pausing ProtocolHandler ["http-nio-8080"]
Stopping service [Tomcat]
Stopping ProtocolHandler ["http-nio-8080"]
Destroying ProtocolHandler ["http-nio-8080"]


Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.


***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.
```

**Comment by Zggis** [comment]
Hi ChoyDarren,

The application will only start on port 8080 within the Docker container. I could make this configurable but it is unnecessary given the following.

You can simply map the container port 8080 to any available port on the host system. Try the following run command:

`docker run -d \
--name=PlexTVTime \
-e SPRING_CONFIG_LOCATION=/config/application.yaml \
-v /volume1/docker/plextvtime:/config \
--net=host \
-p 8081:8080 \
zggis/plex-tvtime:latest`

I run mine on host port 3365, so I know its possible. Keep in mind the application will still believe its running on port 8080 inside the container, and the logs will reflect that, but you should be able to reach that app at http://[host]:8081/

**Comment by Zggis** [comment]
Actually based on the logs I might be wrong, in your case the app might not be running in an isolated Docker container. I use Unraid so its a different setup. I will expose the port through configuration for you, but I feel like there there is probably a better way you can get around this, I just don't know enough about the Synology NAS to guide you.

Give me 45minutes, I will push a change and post an update here when its live.

**Comment by ChoyDarren** [comment]
Thanks for the quick response (and the configuration correction). I did try what you suggested but still got the same error, so I'll wait for your change. Thank you!

**Comment by Zggis** [comment]
I just pushed it to the dev tag, try this command and let me know if it works:

`docker run -d --name=PlexTVTime -e SPRING_CONFIG_LOCATION=/config/application.yaml -e SERVER_PORT=8081 -v /volume1/docker/plextvtime:/config --net=host -p 8081:8081 zggis/plex-tvtime:dev`

If it does I will merge it and publish a new release for latest.

**Comment by ChoyDarren** [comment]
This worked perfectly! Thank you!

**Comment by Zggis** [comment]
Great! I have published the release, please switch back to the latest tag to avoid disruption in the future.

Enjoy the app!
