### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by lacostey86** [Zggis/plex-tvtime#19]
cant login using container manager ( synology 7.2 )
![Screenshot 2024-07-03 050543](https://github.com/Zggis/plex-tvtime/assets/66886262/d80890fb-0ebc-4e42-bd3f-1a0a7dc5c30a)
i put all the information as u can see in the attachment
trying user name as email or number still getting error to login of fetch token 

is there any installation steps for synology ?

**Comment by lacostey86** [comment]
[tvtime.csv](https://github.com/user-attachments/files/16076173/tvtime.csv)

**Comment by Zggis** [comment]
Hi @lacostey86 ,

Looking at the logs you provided the application is not finding the TVTIME_USER environment variable. I was able to replicate this in my local environment by removing the environment variable and I got the same error:
`Logging ${TVTIME_USER} in to TVTime...`
So to be clear, this is not an issue with your email, id, or password.

Unfortunately I don't have a synology, I use Unraid, your screenshot looks correct but something else must be preventing the environment variable seen in your screenshot from getting to the application. If you have an option to configure the Docker command line arguments you can try passing the environment variables in through that:
`-e TVTIME_USER=your_user_name -e TVTIME_PASSWORD=your_password`

**Comment by lacostey86** [comment]
Thanks , I fixed manually as you suggested
