### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by DFBR1208** [Zggis/plex-tvtime#20]
I'm interested in testing the program in my plex, but mine is running in a native windows. Is it supported or only via docker/unraid? Thx!

**Comment by Zggis** [comment]
Its technically possible to run it directly using the latest JAR in [releases](https://github.com/Zggis/plex-tvtime/releases), but that would require you to install Chrome driver and the correct version of Chrome. I found this to be difficult to do, even on my development machine.
If you are really determined to try I can try to help you, but can't make any promises. You will need to install Chrome and the correct version of the driver, figuring out the correct version is documented here: https://developer.chrome.com/docs/chromedriver/downloads/version-selection You will also need to install a JRE17+. You would need to configure all the [environment variables](https://developer.chrome.com/docs/chromedriver/downloads/version-selection) as System environment variables, than you should be able to run the application using:
`java -jar plex-tvtime-210.jar -Dselenium.driver_location="DRIVER-LOCATION" -Dselenium.browser_location="BROWSER-LOCATION'`

The easiest route would probably be to install Docker desktop on the Windows machine, than you can just run the image after adding the environment configuration.

**Comment by DFBR1208** [comment]
Gonna see how to install docker so, it would appreciate if it has a quick and easy way to convert everything (Plex, Sonarr, Radar, etc) to Docker
