### ISSUE TITLE
Google login (no password)

### ISSUE THREAD

**Issue by DFBR1208** [Zggis/plex-tvtime#21]
Hey, so once again I'm here

Manager to install docker but now it's more like a TVTime setting, I created my account via Google OAuth and now I'm not able to generate a password, already trying enter in contact with their support but no result so far, are there any workarounds? Thx!

**Comment by friimaind** [comment]
@DFBR1208 I see that you closed the issue.
How did you fix it?

Thanks

**Comment by DFBR1208** [comment]
Hey, I closed because TVTime answered me, and I was able to login from the page with login and password, I suggest you to just contact TVTime about it
