### ISSUE TITLE
doesn't update series

### ISSUE THREAD

**Issue by leonardopieralli** [Zggis/plex-tvtime#25]
hi, sorry for bothering you. i've noticed that in the latest days (from 28/11/2024) it stopped updating series on tv time and even uninstalling and reinstalling it didn't solve the problem. i've already logged in with the credentials on tv time to be sure that them worked and checked the config on plex media server (which im the only user). from logs i cannot understand whats the problem, the last thing it says it is that due to a media stop on 28/11/2024 he didn't update a serie 

i paste here the html files (oold installation log and new installation log) shared with my google drive
https://drive.google.com/file/d/1QZo-RSiDOBFXdHKJ66Z8RdoOjn9-4F6-/view?usp=drive_link
https://drive.google.com/file/d/1sx78pamwsZtz-F3wKwiAWMDhm7gpkx-x/view?usp=drive_link
hope you could help me solve this problem

**Comment by Zggis** [comment]
Hi @leonardopieralli ,
Please set the environment variable LOGGING_LEVEL to TRACE and replay the tv show that is not updating to capture the logs.

If you can post a snippet of the logs that contain the Plex webhook JSON and the plex-tvtime messages afterward I can take a look.

**Comment by leonardopieralli** [comment]
Sorry for bothering you @Zggis, it seems there was some sort of problem with the server, after a few hours of attempts, i just shut down it, let it unplug for some minutes and when it managed to boot back up, it sent the infos correctly

https://drive.google.com/file/d/1OUHrtikrvrM4JmHFFY9jNJRKezn0QQxD/view?usp=drive_link
i attach the new log (the logging_level variable is still on debug because the problem was solved, i simply attach it to give "extra data" to a developer in case of need) 
very thanks for your help and your response speed
